version: '3'

services:
  devct:
    build:
      context: .
      dockerfile: Containerfile
    image: devct
    container_name: devct
    hostname: "devct"
    command: sh -c "tail -f /dev/null"
    restart: always
    volumes:
      - local_share:/home/connor/.local/share
      - ssh:/home/connor/.ssh
      - ${HOME}:/out

volumes:
  local_share:
    name: "devct_local_share"
  ssh:
    name: "devct_ssh"
