version: '3'

services:
  devct:
    build:
      context: .
      dockerfile: Containerfile
      args:
        USERNAME: ${USERNAME}
    image: devct
    container_name: devct
    hostname: "devct"
    command: sh -c "tail -f /dev/null"
    restart: always
    ports:
      - "127.0.0.1:1313:1313" # hugo
    volumes:
      - local_share:/home/${USERNAME}/.local/share
      - ssh:/home/${USERNAME}/.ssh
      - code:/home/${USERNAME}/code
      - emacs:/home/${USERNAME}/.emacs.d
      - doom_emacs:/home/${USERNAME}/.doom.d
      - ${HOME}:/out

volumes:
  local_share:
    name: "devct_local_share"
  ssh:
    name: "devct_ssh"
  code:
    name: "code"
  emacs:
    name: "devct_emacs"
  doom_emacs:
    name: "devct_doom_emacs"
