version: '3'

services:
  devct:
    build:
      context: .
      dockerfile: Containerfile
      args:
        PASS: ${PASS}
    image: devct
    container_name: devct
    hostname: "devct"
    volumes:
      - devct_persist:/home/connor/.local/share
      - ${HOME}:/out

volumes:
  devct_persist:
    name: "devct_persist"
